import { ReactNode, Suspense } from 'react';

import type { Metadata } from 'next';
import { Document } from '~/app/Document';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <Document>
      <Suspense>{children}</Suspense>
    </Document>
  );
}
